### ISSUE TITLE
Error mining C31 on VEGA64 ROCm + Ubuntu 18.04

### ISSUE THREAD

**Issue by rsguru** [mimblewimble/grin-miner#163] opened 2019-01-24 21:10 UTC
###################### OPENCL PROGRAM BUILD DEBUG OUTPUT ######################

Config file is:
[[mining.miner_plugin_config]]
plugin_name = "ocl_cuckatoo"
[mining.miner_plugin_config.parameters]
platform = 1
device = 1
edge_bits = 31

Error: Failed to compile opencl source (from CL to LLVM IR).
###############################################################################

', libcore/result.rs:1009:5
/tmp/AMD_1466_140/t_1466_142.cl:55:15: error: variables in the local address space can only be declared
	  in the outermost scope of a kernel function
				__local u32 el[256][8];
							^
1 error generated.
thread '<unnamed>' panicked at 'can't build trimmer: 
.......................................................................................................................

If I run with AMD driver 18.30, it works but I get just 0.17 GPS

**Comment by the-babaji** [comment] 2019-02-01 03:54
with the amd radeon drivers 18.50  i get 1.73 or so (C31) on a vega56, do you think if we can get ROCM to work, you would expect to see a boost in GPS?

**Comment by LuckyX2** [comment] 2019-02-06 07:07
> with the amd radeon drivers 18.50 i get 1.73 or so (C31) on a vega56, do you think if we can get ROCM to work, you would expect to see a boost in GPS?

1.73gps on a Vega56? are you sure you don't mean C29? C31 shouldn't even be able to run on a Vega56 since it only has 8GB of memory and 11GB is needed, let alone as fast as a 2080Ti (they get ~1.7gps on C31)

I think why rsguru can run C31 with the non-ROCm driver is cause that probably has HBCC allowing it to address more than the 8GB of VRAM. This would explain why it runs but very slowly since 3GB of it is loaded in system memory. Just a guess. It's possible the ROCm driver doesn't enable HBCC.

**Comment by the-babaji** [comment] 2019-02-06 15:47
Hi Lucky, 
Thanks for catching that. I put the decimal point in the wrong place. The Vega56 mines 0.17 GPS31.

You can mine with less than 11gb, i have some 4gb amd cards also mining C31, using the ocl_cuckatoo plugin.  (last plugin inthe grin-miner.toml file)

The Vega56 mines C29 @ 2.9 GPS, which returns significantly (50%) more grin per hour, so I am leaving it there.

**Comment by LuckyX2** [comment] 2019-02-06 18:55
I believe the error is associated with the ocl-icd-libopencl1 and or ocl-icd-opencl-dev package. I compiled with ROCm installed, saw the C31 failure you did, uninstalled ROCm, uninstalled and reinstalled amdgpu-pro (version 18.50), recompiled and still had the same problem, implying something remained from the ROCm install since a fresh amdgpu-pro install works fine. I noticed that after uninstalling amdgpu-pro, the two previously mentioned packages are still installed, hence me thinking that's where the issue is.

**Comment by LuckyX2** [comment] 2019-02-06 23:13
I moved the line `__local u32 el[256][8];` up in scope (I put it below the line` const int lid = get_local_id(0);`) in Cuckatoo's trimmer.rs and it builds and runs fine for me now.

I also had to symlink the ROCm OpenCL lib since it wasn't in /usr/libs where it's expected.
`sudo ln -s /opt/rocm/opencl/lib/x86_64/libOpenCL.so /usr/lib/libOpenCL.so`

**Comment by the-babaji** [comment] 2019-02-06 23:46
good job, does the ROCM yield any increase in GPS over the AMD drivers?

**Comment by LuckyX2** [comment] 2019-02-12 02:10
> good job, does the ROCM yield any increase in GPS over the AMD drivers?
I've seen no improvement.

@rsguru this should be fixed now if you could close it.

**Comment by quentinlesceller** [comment] 2020-03-09 11:35
Closing. Feel free to reopen if this is still relevant.

**Closed by quentinlesceller** 2020-03-09 11:35 UTC
