### ISSUE TITLE
RpcError 32502

### ISSUE THREAD

**Issue by Jaschenn** [mimblewimble/grin-miner#222] opened 2019-07-23 07:14 UTC
Today I try to run the miner (with GrinMint), and i get a error
The error is like this: 
```
ERRO Failed to submit a solution: RpcError { code: -32502, message: "Failed to validate solution" } 
```

some useful messages:
```

Jul 23 14:43:06.010 DEBG Received response with id: 0
Jul 23 14:43:06.010 ERRO Failed to submit a solution: RpcError { code: -32502, message: "Failed to validate solution" }
Jul 23 14:43:06.010 DEBG Received message: {"id":"Stratum","jsonrpc":"2.0","method":"job","params":{"height":270495,"job_id":2,"difficulty":4,"pre_pow":"0002000000000004209f000000005d36ac7c000002b1b2da764aee23ccf547ddfb35fc47c505a215f2b73eb2170fe8c255735fc4b8c3aa83259fcdf075d0ec8e9f78c7f632c0cc0895a1d387fcad328a5c635d72fb90d104ece6f92b6d336bc1932229c1fa7d42fd546dbe5a9fc654486a69274cfd1ca13b7125ad35769d425bf446886e8845076d53a36d315b26e56637f87db4699440c6caf59ca11ef4b66a940630d4330fb54970431c1cf51df95ab3935f4c905ba727f6e0447475115bed7e98144a953ca4d7e5f01e0c9db043d02d1900000000002f91a5000000000018dd120002cd8062000338000002af"}}
```

```

Jul 23 14:47:56.005 DEBG Received request type: job
Jul 23 14:47:56.005 INFO Got a new job: JobTemplate { height: 270499, job_id: 0, difficulty: 4, pre_pow: "000200000000000420a3000000005d36ad9c000003c74076909148b94ff0399ffe23d2fe9e1be91d9108aed3589fb3dbbe03632b23b72870f074eaa322f15312b0abfb2614773961e92e41ecede39e21ac74a1865597a52588c495999de63602f1cc2f754ec7bb42e13300b2081c4f558d58868eab123eec1cd7cda9cd391645d627e09df9924132fc58a0d97ecc3df8f877728911bd2d79579a60485cf07f0bd8f6b3379da7bc2035c6ed12af0ff193521e1dd84e55ce09a27157a496ed1372354ef5331ac57e1ea4ecf3bc11118bdde44e00000000002f91eb000000000018dd3b0002cd829ec2932f000002af" }
Jul 23 14:47:56.008 DEBG Miner received message: ReceivedJob(270499, 0, 4, "000200000000000420a3000000005d36ad9c000003c74076909148b94ff0399ffe23d2fe9e1be91d9108aed3589fb3dbbe03632b23b72870f074eaa322f15312b0abfb2614773961e92e41ecede39e21ac74a1865597a52588c495999de63602f1cc2f754ec7bb42e13300b2081c4f558d58868eab123eec1cd7cda9cd391645d627e09df9924132fc58a0d97ecc3df8f877728911bd2d79579a60485cf07f0bd8f6b3379da7bc2035c6ed12af0ff193521e1dd84e55ce09a27157a496ed1372354ef5331ac57e1ea4ecf3bc11118bdde44e00000000002f91eb000000000018dd3b0002cd829ec2932f000002af")
Jul 23 14:47:56.008 DEBG Pause message sent
Jul 23 14:47:56.009 DEBG Resume message sent
Jul 23 14:47:56.009 DEBG Mining: Plugin 0 - Device 0 (CPU) at Cuck(at)oo29 - Status: OK : Last Graph time: 7.24109549s; Graphs per second: 0.138 - Total Attempts: 155
Jul 23 14:47:56.009 INFO Mining: Cuck(at)oo at 0.13810065084502843 gps (graphs per second)
Jul 23 14:47:56.282 DEBG solver_thread - solver_loop_rx got msg: Pause
Jul 23 14:47:56.282 DEBG solver_thread - solver_loop_rx got msg: Resume
Jul 23 14:47:57.004 DEBG sending request: {"id":"0","jsonrpc":"2.0","method":"status","params":null}
Jul 23 14:47:58.006 DEBG Received message: {"id":"0","jsonrpc":"2.0","method":"status","result":{"id":"miner","height":270499,"difficulty":4,"accepted":0,"rejected":1,"stale":0}}
```

I have upgrade grin-miner to the lasted

**Comment by quentinlesceller** [comment] 2019-07-23 08:43
Hi @Jaschenn. Which plugin are you using? You must use cuckarood29. Cuckaroo29 is no longer used by Grin.

**Comment by Jaschenn** [comment] 2019-07-23 08:52
the config are as follows:
```
[[mining.miner_plugin_config]]
plugin_name = "cuckaroo_cpu_avx2_29"
[mining.miner_plugin_config.parameters]
nthreads = 4
```
Maybe this is the reason.
And where can i get `cuckarood29`?

**Comment by quentinlesceller** [comment] 2019-07-23 09:38
Take a look at here https://github.com/mimblewimble/grin-miner/blob/master/grin-miner.toml#L107.
This is where you can enable `cuckarood29` plugin. There is no CPU equivalent right now, only Nvidia miner. I'm going to close this issue since it's not a bug or a requested feature. Thanks! You can continue to comment here if you have any question.

**Closed by quentinlesceller** 2019-07-23 09:38 UTC
