### ISSUE TITLE
won't hash on gpu

### ISSUE THREAD

**Issue by kelliblueeyes** [mimblewimble/grin-miner#235] opened 2019-12-30 18:17 UTC
I've tried both the v3 beta and the v2. Compiled from source on mac os x catalina. The cpus work fine, the gpu won't hash.

I've got a 2010 mac pro with a sapphire radeon pulse rx580 8GB on catalina.
 
I followed your instructions in the read me, and also here:
https://www.grin-forum.org/t/grin-v1-0-step-by-step-miner-guide-on-macos-english-version/1630

the miner usually starts with no error, device 0 shows for gpu, connects to the pool and receives work, but it won't hash, says inf.

Screenshots are here:
https://www.grin-forum.org/t/gpu-wont-hash-mac-os-catalina/6801

**Comment by quentinlesceller** [comment] 2020-01-06 21:03
Did you compile the miner yourself? Instructions above are likely outdated.

**Comment by kelliblueeyes** [comment] 2020-01-06 21:08
I did compile the official grin miner on macos catalina with the instructions on git hub
I posted about it on the grin forum and the people who replied to the thread said it looked like I followed the insteructions
Probably doesn't matter, as I was only ever able to get the cpus to mine at .22gps even though the miner was reporting I was finding shares, never was able to get my gpu to work.
Some people said it may be the pool connection issue, since the grinmint website wasn't reporting the hash I was producing, and not really that the gpu wouldn't mine. So they advised me to contact pool support about the connection issue before spending more time on the gpu

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by quentinlesceller** [comment] 2020-01-06 21:09
I'm the pool manager of Grinmint and by the look of it it looks like your GPU is mining at all so Grinmint will not show you anything.
Did you uncomment this line before compiling? https://github.com/mimblewimble/grin-miner/blob/master/Cargo.toml#L40

**Comment by kelliblueeyes** [comment] 2020-01-06 21:13
I actually re-compiled the binary numerous times with different options while I was trying to troubleshoot the issue, probably, unless that was in the read.me on github I did not compile without uncommenting that line.
I will try doing that, and see if it will work

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by quentinlesceller** [comment] 2020-01-06 21:15
Without that line you will not compile any GPU mining plugin (so no GPU mining can be done).

**Comment by kelliblueeyes** [comment] 2020-01-06 21:22
umm, ok.
I just pulled the code off github (again) I can't find that line in any of the files.
I did compile the opencl plugins, and I can get the sevice to show up, but not labled as a gpu

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by kelliblueeyes** [comment] 2020-01-06 21:24
You mean these pluging, correct?

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by quentinlesceller** [comment] 2020-01-06 21:31
It's in the main Cargo.toml

**Comment by quentinlesceller** [comment] 2020-01-06 21:31
Sorry I just notice you were trying to mine with the OpenCL plugin. Give me some time to check a few things...

**Comment by kelliblueeyes** [comment] 2020-01-06 21:33
the only line in that file that's commented out are the cuda pluggins, I'm using opencl

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by kelliblueeyes** [comment] 2020-01-06 21:47
I just recompiled from source with the instructions on github, noticed something interesting you may like to know

git clone
https://github.com/mimblewimble/grin-miner.git

cd

grin-miner
git submodule update --init
cargo build

cargo build --features opencl

./install_ocl_plugins.sh

Doing this builds the binary in ~/grin-miner/target/debug

but builds all the opencl stuff in ~/grin-miner/target/release

I've been cp'ing the opencl stuff from release folder to the debug folder to run the program with opencl, but I assume they're meant to end up in the same directory

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by quentinlesceller** [comment] 2020-01-06 21:48
Can you compile with `cargo build --features opencl --release` ?

**Comment by kelliblueeyes** [comment] 2020-01-06 22:00
ok, I did that, still wind up with this:
(see attachments tried with both ocl-cuckaroo and cuckatoo plugins),
and no report of any activity on the grinmint dashboard

grin miner.toml

[[mining.miner_plugin_config]]
plugin_name = "cuckarood_cpu_compat_29"
[mining.miner_plugin_config.parameters]
nthreads = 8

[[mining.miner_plugin_config]]
plugin_name = "ocl_cuckaroo"
[mining.miner_plugin_config.parameters]
platform = 1
device = 0

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by quentinlesceller** [comment] 2020-01-06 22:29
Any idea @hashmap ?

**Comment by kelliblueeyes** [comment] 2020-02-02 15:32
A mac developer who's also into mining looked at the grin miner and says:

"I had look at grin-miner and it seems the AMD side of things requires the drivers which aren't available for macOS so unfortunately unless there's another miner around which doesn't that's not going to work right now. The majority of algorithms have this issue which makes GPU mining on Mac more than a little tricky."

**Comment by quentinlesceller** [comment] 2020-03-09 11:41
It's looks like macOS use a very old version of openCL. Closing, probably duplicate of #199

**Closed by quentinlesceller** 2020-03-09 11:41 UTC
