### ISSUE TITLE
Only 1 solution accepted on pool [Grinmint]

### ISSUE THREAD

**Issue by perry-mitchell** [mimblewimble/grin-miner#193] opened 2019-02-15 07:11 UTC
Hi,

I'm using the latest version (1.0.2) to mine with 16x 1070tis on Grinmint, which was working fine until earlier this week when 1 miner simply stopped having it's solutions accepted. I restarted the second rig (we have 2) and it also started dying like this. The log is as follows (fresh start):

```
Feb 15 09:06:45.624 INFO This is Grin-Miner version 1.0.2 (git v1.0.2), built for x86_64-unknown-linux-gnu by rustc 1.31.1 (b6c32da9b 2018-12-18).
Feb 15 09:06:45.624 DEBG Built with profile "release", features "CURSIVE, DEFAULT, OCL_CUCKAROO, OCL_CUCKATOO, OPENCL, TUI" on Thu, 17 Jan 2019 09:43:20 GMT.
Feb 15 09:06:45.625 DEBG Starting solvers
Feb 15 09:06:45.625 DEBG No mining plugin dir provided by config. Using default plugin dir: "/home/<snip>/grin/grin-miner-v1.0.2/plugins"
Feb 15 09:06:45.625 DEBG Loading miner plugin: /home/<snip>/grin/grin-miner-v1.0.2/plugins/cuckaroo_cuda_29.cuckooplugin
Feb 15 09:06:45.625 DEBG Loading miner plugin: /home/<snip>/grin/grin-miner-v1.0.2/plugins/cuckaroo_cuda_29.cuckooplugin
Feb 15 09:06:45.625 DEBG Loading miner plugin: /home/<snip>/grin/grin-miner-v1.0.2/plugins/cuckaroo_cuda_29.cuckooplugin
Feb 15 09:06:45.625 DEBG Loading miner plugin: /home/<snip>/grin/grin-miner-v1.0.2/plugins/cuckaroo_cuda_29.cuckooplugin
Feb 15 09:06:45.625 DEBG Loading miner plugin: /home/<snip>/grin/grin-miner-v1.0.2/plugins/cuckaroo_cuda_29.cuckooplugin
Feb 15 09:06:45.625 DEBG Loading miner plugin: /home/<snip>/grin/grin-miner-v1.0.2/plugins/cuckaroo_cuda_29.cuckooplugin
Feb 15 09:06:45.625 DEBG Loading miner plugin: /home/<snip>/grin/grin-miner-v1.0.2/plugins/cuckaroo_cuda_29.cuckooplugin
Feb 15 09:06:45.625 DEBG Loading miner plugin: /home/<snip>/grin/grin-miner-v1.0.2/plugins/cuckaroo_cuda_29.cuckooplugin
Feb 15 09:06:45.625 DEBG Loading miner plugin: /home/<snip>/grin/grin-miner-v1.0.2/plugins/cuckaroo_cuda_29.cuckooplugin
Feb 15 09:06:45.625 DEBG Loading miner plugin: /home/<snip>/grin/grin-miner-v1.0.2/plugins/cuckaroo_cuda_29.cuckooplugin
Feb 15 09:06:45.625 DEBG Loading miner plugin: /home/<snip>/grin/grin-miner-v1.0.2/plugins/cuckaroo_cuda_29.cuckooplugin
Feb 15 09:06:45.625 DEBG Loading miner plugin: /home/<snip>/grin/grin-miner-v1.0.2/plugins/cuckaroo_cuda_29.cuckooplugin
Feb 15 09:06:45.625 DEBG Loading miner plugin: /home/<snip>/grin/grin-miner-v1.0.2/plugins/cuckaroo_cuda_29.cuckooplugin
Feb 15 09:06:45.625 DEBG Loading miner plugin: /home/<snip>/grin/grin-miner-v1.0.2/plugins/cuckaroo_cuda_29.cuckooplugin
Feb 15 09:06:45.626 DEBG Loading miner plugin: /home/<snip>/grin/grin-miner-v1.0.2/plugins/cuckaroo_cuda_29.cuckooplugin
Feb 15 09:06:45.626 DEBG Loading miner plugin: /home/<snip>/grin/grin-miner-v1.0.2/plugins/cuckaroo_cuda_29.cuckooplugin
Feb 15 09:06:46.765 WARN Connection Status: Connected to Grin server at eu-west-stratum.grinmint.com:4416.
Feb 15 09:06:46.775 DEBG sending request: {"id":"0","jsonrpc":"2.0","method":"login","params":{"agent":"grin-miner","login":"<snip>/rig01","pass":"<snip>"}}
Feb 15 09:06:46.775 DEBG sending request: {"id":"0","jsonrpc":"2.0","method":"getjobtemplate","params":null}
Feb 15 09:06:47.007 DEBG Received message: {"id":"0","jsonrpc":"2.0","method":"login","result":"ok"}

Feb 15 09:06:47.007 DEBG Received response with id: 0
Feb 15 09:06:47.007 DEBG Received message: {"id":"0","jsonrpc":"2.0","method":"getjobtemplate","result":{"height":43871,"job_id":8,"difficulty":4,"pre_pow":"0001000000000000ab5f000000005c666500000001274a37e9adcf91de7c881c7695941bcfc3a26154094137429b446f34d9c445e637673bb39148e4925be003a46ca5116c600cd6096c554acb1ce01c3554526de5a1b89e96c1cdf9406c322de463e84f6ea173464102956a96f7b6c5ff0e82c32ca47eb1130efad97f1b8309bed4ed196e6f267afba26800ec13118049e97f5d9c49c111e7770e06bca73acb93be0bbc9a391d8d887e1f250e0bb1facde8501de666fb1a0b43b83b08bb6f483853228888c9c57eff03bdfa0f428379f15900000000000d5c1000000000000506120000451cd76b15a400000359"}}

Feb 15 09:06:47.007 DEBG Received response with id: 0
Feb 15 09:06:47.007 INFO Got a job at height 43871 and difficulty 4
Feb 15 09:06:47.036 DEBG Miner received message: ReceivedJob(43871, 8, 4, "0001000000000000ab5f000000005c666500000001274a37e9adcf91de7c881c7695941bcfc3a26154094137429b446f34d9c445e637673bb39148e4925be003a46ca5116c600cd6096c554acb1ce01c3554526de5a1b89e96c1cdf9406c322de463e84f6ea173464102956a96f7b6c5ff0e82c32ca47eb1130efad97f1b8309bed4ed196e6f267afba26800ec13118049e97f5d9c49c111e7770e06bca73acb93be0bbc9a391d8d887e1f250e0bb1facde8501de666fb1a0b43b83b08bb6f483853228888c9c57eff03bdfa0f428379f15900000000000d5c1000000000000506120000451cd76b15a400000359")
Feb 15 09:06:47.036 DEBG Pause message sent
Feb 15 09:06:47.036 DEBG Resume message sent
Feb 15 09:06:48.037 DEBG Mining: Plugin 0 - Device 0 () at Cuck(at)oo0 - Status: OK : Last Graph time: 0s; Graphs per second: inf - Total Attempts: 0
Feb 15 09:06:48.037 DEBG Mining: Plugin 1 - Device 0 () at Cuck(at)oo0 - Status: OK : Last Graph time: 0s; Graphs per second: inf - Total Attempts: 0
Feb 15 09:06:48.037 DEBG Mining: Plugin 2 - Device 0 () at Cuck(at)oo0 - Status: OK : Last Graph time: 0s; Graphs per second: inf - Total Attempts: 0
Feb 15 09:06:48.037 DEBG Mining: Plugin 3 - Device 0 () at Cuck(at)oo0 - Status: OK : Last Graph time: 0s; Graphs per second: inf - Total Attempts: 0
Feb 15 09:06:48.037 DEBG Mining: Plugin 4 - Device 0 () at Cuck(at)oo0 - Status: OK : Last Graph time: 0s; Graphs per second: inf - Total Attempts: 0
Feb 15 09:06:48.037 DEBG Mining: Plugin 5 - Device 0 () at Cuck(at)oo0 - Status: OK : Last Graph time: 0s; Graphs per second: inf - Total Attempts: 0
Feb 15 09:06:48.037 DEBG Mining: Plugin 6 - Device 0 () at Cuck(at)oo0 - Status: OK : Last Graph time: 0s; Graphs per second: inf - Total Attempts: 0
Feb 15 09:06:48.037 DEBG Mining: Plugin 7 - Device 0 () at Cuck(at)oo0 - Status: OK : Last Graph time: 0s; Graphs per second: inf - Total Attempts: 0
Feb 15 09:06:48.037 INFO Mining: Cuck(at)oo at 0 gps (graphs per second)
Feb 15 09:06:51.007 DEBG Received message: {"id":"Stratum","jsonrpc":"2.0","method":"job","params":{"height":43872,"job_id":0,"difficulty":4,"pre_pow":"0001000000000000ab60000000005c66650800000322ed82816fc6152c49bfc6b8bc1a0032ae8f383547300651f60becdebb212654d3d0fabac37cff93c92f6f8f03e3fc7c2b19f65c4eea59873ccee599e9aba20108e5ed68905d1d3d96b49adce84a37db7f3355490f2e9a9d27fadade944591cdac0ecfaeed8365e3d278358bb89066c707e5ef3715fbd69a10b6d9ce2e63eac87ac6ce1cbdb900d316048ff9c46177f690a3d4c31cd8da8188a60b6f7d501de666fb1a0b43b83b08bb6f483853228888c9c57eff03bdfa0f428379f15900000000000d5c1200000000000506130000451d8fa95e1500000357"}}

Feb 15 09:06:51.007 DEBG Received request type: job
Feb 15 09:06:51.007 INFO Got a new job: JobTemplate { height: 43872, job_id: 0, difficulty: 4, pre_pow: "0001000000000000ab60000000005c66650800000322ed82816fc6152c49bfc6b8bc1a0032ae8f383547300651f60becdebb212654d3d0fabac37cff93c92f6f8f03e3fc7c2b19f65c4eea59873ccee599e9aba20108e5ed68905d1d3d96b49adce84a37db7f3355490f2e9a9d27fadade944591cdac0ecfaeed8365e3d278358bb89066c707e5ef3715fbd69a10b6d9ce2e63eac87ac6ce1cbdb900d316048ff9c46177f690a3d4c31cd8da8188a60b6f7d501de666fb1a0b43b83b08bb6f483853228888c9c57eff03bdfa0f428379f15900000000000d5c1200000000000506130000451d8fa95e1500000357" }
Feb 15 09:06:51.065 DEBG Miner received message: ReceivedJob(43872, 0, 4, "0001000000000000ab60000000005c66650800000322ed82816fc6152c49bfc6b8bc1a0032ae8f383547300651f60becdebb212654d3d0fabac37cff93c92f6f8f03e3fc7c2b19f65c4eea59873ccee599e9aba20108e5ed68905d1d3d96b49adce84a37db7f3355490f2e9a9d27fadade944591cdac0ecfaeed8365e3d278358bb89066c707e5ef3715fbd69a10b6d9ce2e63eac87ac6ce1cbdb900d316048ff9c46177f690a3d4c31cd8da8188a60b6f7d501de666fb1a0b43b83b08bb6f483853228888c9c57eff03bdfa0f428379f15900000000000d5c1200000000000506130000451d8fa95e1500000357")
Feb 15 09:06:51.065 DEBG Pause message sent
Feb 15 09:06:51.065 DEBG Resume message sent
Feb 15 09:06:51.065 DEBG Mining: Plugin 0 - Device 0 () at Cuck(at)oo0 - Status: OK : Last Graph time: 0s; Graphs per second: inf - Total Attempts: 0
Feb 15 09:06:51.065 DEBG Mining: Plugin 1 - Device 0 () at Cuck(at)oo0 - Status: OK : Last Graph time: 0s; Graphs per second: inf - Total Attempts: 0
Feb 15 09:06:51.065 DEBG Mining: Plugin 2 - Device 0 () at Cuck(at)oo0 - Status: OK : Last Graph time: 0s; Graphs per second: inf - Total Attempts: 0
Feb 15 09:06:51.065 DEBG Mining: Plugin 3 - Device 0 () at Cuck(at)oo0 - Status: OK : Last Graph time: 0s; Graphs per second: inf - Total Attempts: 0
Feb 15 09:06:51.065 DEBG Mining: Plugin 4 - Device 0 () at Cuck(at)oo0 - Status: OK : Last Graph time: 0s; Graphs per second: inf - Total Attempts: 0
Feb 15 09:06:51.065 DEBG Mining: Plugin 5 - Device 0 () at Cuck(at)oo0 - Status: OK : Last Graph time: 0s; Graphs per second: inf - Total Attempts: 0
Feb 15 09:06:51.065 DEBG Mining: Plugin 6 - Device 0 () at Cuck(at)oo0 - Status: OK : Last Graph time: 0s; Graphs per second: inf - Total Attempts: 0
Feb 15 09:06:51.065 DEBG Mining: Plugin 7 - Device 0 () at Cuck(at)oo0 - Status: OK : Last Graph time: 0s; Graphs per second: inf - Total Attempts: 0
Feb 15 09:06:51.065 INFO Mining: Cuck(at)oo at 0 gps (graphs per second)
Feb 15 09:06:51.229 DEBG solver_thread - solver_loop_rx got msg: Pause
Feb 15 09:06:51.229 DEBG solver_thread - solver_loop_rx got msg: Resume
Feb 15 09:06:51.409 DEBG solver_thread - solver_loop_rx got msg: Pause
Feb 15 09:06:51.409 DEBG solver_thread - solver_loop_rx got msg: Resume
Feb 15 09:06:51.428 DEBG solver_thread - solver_loop_rx got msg: Pause
Feb 15 09:06:51.428 DEBG solver_thread - solver_loop_rx got msg: Resume
Feb 15 09:06:51.448 DEBG solver_thread - solver_loop_rx got msg: Pause
Feb 15 09:06:51.448 DEBG solver_thread - solver_loop_rx got msg: Resume
Feb 15 09:06:51.452 DEBG solver_thread - solver_loop_rx got msg: Pause
Feb 15 09:06:51.453 DEBG solver_thread - solver_loop_rx got msg: Resume
Feb 15 09:06:51.453 DEBG solver_thread - solver_loop_rx got msg: Pause
Feb 15 09:06:51.453 DEBG solver_thread - solver_loop_rx got msg: Resume
Feb 15 09:06:51.455 DEBG solver_thread - solver_loop_rx got msg: Pause
Feb 15 09:06:51.455 DEBG solver_thread - solver_loop_rx got msg: Resume
Feb 15 09:06:51.463 DEBG solver_thread - solver_loop_rx got msg: Pause
Feb 15 09:06:51.463 DEBG solver_thread - solver_loop_rx got msg: Resume
Feb 15 09:06:51.590 DEBG solver_thread - solver_loop_rx got msg: Pause
Feb 15 09:06:51.591 DEBG solver_thread - solver_loop_rx got msg: Resume
Feb 15 09:06:51.801 DEBG solver_thread - solver_loop_rx got msg: Pause
Feb 15 09:06:51.801 DEBG solver_thread - solver_loop_rx got msg: Resume
Feb 15 09:06:51.804 DEBG solver_thread - solver_loop_rx got msg: Pause
Feb 15 09:06:51.815 DEBG solver_thread - solver_loop_rx got msg: Resume
Feb 15 09:06:51.828 DEBG solver_thread - solver_loop_rx got msg: Pause
Feb 15 09:06:51.833 DEBG solver_thread - solver_loop_rx got msg: Resume
Feb 15 09:06:51.834 DEBG solver_thread - solver_loop_rx got msg: Pause
Feb 15 09:06:51.835 DEBG solver_thread - solver_loop_rx got msg: Pause
Feb 15 09:06:51.835 DEBG solver_thread - solver_loop_rx got msg: Resume
Feb 15 09:06:51.836 DEBG solver_thread - solver_loop_rx got msg: Resume
Feb 15 09:06:51.836 DEBG solver_thread - solver_loop_rx got msg: Pause
Feb 15 09:06:51.837 DEBG solver_thread - solver_loop_rx got msg: Resume
Feb 15 09:06:51.840 DEBG solver_thread - solver_loop_rx got msg: Pause
Feb 15 09:06:51.840 DEBG solver_thread - solver_loop_rx got msg: Resume
Feb 15 09:06:54.068 DEBG Mining: Plugin 0 - Device 0 (GeForce GTX 1070 Ti) at Cuck(at)oo29 - Status: OK : Last Graph time: 0.324386511s; Graphs per second: 3.083 - Total Attempts: 7
Feb 15 09:06:54.068 DEBG Mining: Plugin 1 - Device 1 (GeForce GTX 1070 Ti) at Cuck(at)oo29 - Status: OK : Last Graph time: 0.346741985s; Graphs per second: 2.884 - Total Attempts: 8
Feb 15 09:06:54.068 DEBG Mining: Plugin 2 - Device 2 (GeForce GTX 1070 Ti) at Cuck(at)oo29 - Status: OK : Last Graph time: 0.330606296s; Graphs per second: 3.025 - Total Attempts: 7
Feb 15 09:06:54.068 DEBG Mining: Plugin 3 - Device 3 (GeForce GTX 1070 Ti) at Cuck(at)oo29 - Status: OK : Last Graph time: 0.34982653s; Graphs per second: 2.859 - Total Attempts: 7
Feb 15 09:06:54.068 DEBG Mining: Plugin 4 - Device 4 (GeForce GTX 1070 Ti) at Cuck(at)oo29 - Status: OK : Last Graph time: 0.3417542s; Graphs per second: 2.926 - Total Attempts: 7
Feb 15 09:06:54.068 DEBG Mining: Plugin 5 - Device 5 (GeForce GTX 1070 Ti) at Cuck(at)oo29 - Status: OK : Last Graph time: 0.326132875s; Graphs per second: 3.066 - Total Attempts: 7
Feb 15 09:06:54.068 DEBG Mining: Plugin 6 - Device 6 (GeForce GTX 1070 Ti) at Cuck(at)oo29 - Status: OK : Last Graph time: 0.360896725s; Graphs per second: 2.771 - Total Attempts: 7
Feb 15 09:06:54.068 DEBG Mining: Plugin 7 - Device 7 (GeForce GTX 1070 Ti) at Cuck(at)oo29 - Status: OK : Last Graph time: 0.341322743s; Graphs per second: 2.930 - Total Attempts: 7
Feb 15 09:06:54.068 INFO Mining: Cuck(at)oo at 23.543005169457697 gps (graphs per second)
Feb 15 09:06:55.075 DEBG Client received message: FoundSolution(43872, 0, 29, 1191231682128934082, [11626284, 34214977, 48808935, 53928810, 54941437, 58859766, 108223836, 176970066, 194761811, 202060571, 208505509, 209501546, 210730905, 211101007, 213473628, 254607639, 256004129, 261037362, 263390775, 264000815, 266535356, 279209743, 284297175, 293477809, 324186675, 333287030, 335215638, 340521632, 343751739, 392028586, 403653471, 409593901, 410753050, 411599128, 412509604, 458533037, 483996242, 491066848, 492562200, 501575575, 513045629, 521536163])
Feb 15 09:06:55.075 DEBG sending request: {"id":"0","jsonrpc":"2.0","method":"submit","params":{"edge_bits":29,"height":43872,"job_id":0,"nonce":1191231682128934082,"pow":[11626284,34214977,48808935,53928810,54941437,58859766,108223836,176970066,194761811,202060571,208505509,209501546,210730905,211101007,213473628,254607639,256004129,261037362,263390775,264000815,266535356,279209743,284297175,293477809,324186675,333287030,335215638,340521632,343751739,392028586,403653471,409593901,410753050,411599128,412509604,458533037,483996242,491066848,492562200,501575575,513045629,521536163]}}
Feb 15 09:06:57.007 DEBG Received message: {"id":"0","jsonrpc":"2.0","method":"submit","result":"ok"}

Feb 15 09:06:57.007 DEBG Received response with id: 0
Feb 15 09:06:57.007 INFO Share Accepted!!
Feb 15 09:06:57.007 DEBG Received message: 

Feb 15 09:06:57.027 ERRO 
thread 'client_controller' panicked at 'called `Result::unwrap()` on an `Err` value: Error("EOF while parsing a value", line: 2, column: 0)': libcore/result.rs:1009stack backtrace:
   0:     0x56493881863d - backtrace::backtrace::trace::h6a895d5d279a8d2f
   1:     0x564938817852 - <backtrace::capture::Backtrace as core::default::Default>::default::h03a8d770395d927e
   2:     0x5649388178c9 - backtrace::capture::Backtrace::new::h2eb1c11c92f206be
   3:     0x5649387ec420 - grin_miner_util::logger::send_panic_to_log::{{closure}}::h4bb1012a1843d723
   4:     0x564938844f56 - std::panicking::rust_panic_with_hook::hde420d6fd4455550
                        at libstd/panicking.rs:480
   5:     0x564938844aa1 - std::panicking::continue_panic_fmt::h8f394f3c578bcc76
                        at libstd/panicking.rs:390
   6:     0x564938844985 - rust_begin_unwind
                        at libstd/panicking.rs:325
   7:     0x56493888b64c - core::panicking::panic_fmt::hca5dc4e8b320bc56
                        at libcore/panicking.rs:77
   8:     0x56493874027e - core::result::unwrap_failed::h676613393beddaff
   9:     0x5649386ef29f - grin_miner::client::Controller::run::h2d80e4893dd1fee2
  10:     0x56493870c273 - std::sys_common::backtrace::__rust_begin_short_backtrace::hb4b8ef8be700886b
  11:     0x56493871c588 - std::panicking::try::do_call::h26b7446fed7a5990
  12:     0x564938854fe9 - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:102
  13:     0x56493872ade7 - <F as alloc::boxed::FnBox<A>>::call_box::hbcb2a2093a904eb3
  14:     0x5649388423ad - <alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Output=R> + 'a)> as core::ops::function::FnOnce<A>>::call_once::h9d902c911a417e39
                        at liballoc/boxed.rs:682
                         - std::sys_common::thread::start_thread::h44127e03e78ca137
                        at libstd/sys_common/thread.rs:24
  15:     0x5649388336c5 - std::sys::unix::thread::Thread::new::thread_start::h8f17b97f2223146c
                        at libstd/sys/unix/thread.rs:90
  16:     0x7f2eafd866b9 - start_thread
  17:     0x7f2eaf8a641c - clone
  18:                0x0 - <unknown>


Feb 15 09:06:57.077 DEBG Mining: Plugin 0 - Device 0 (GeForce GTX 1070 Ti) at Cuck(at)oo29 - Status: OK : Last Graph time: 0.327743213s; Graphs per second: 3.051 - Total Attempts: 16
Feb 15 09:06:57.078 DEBG Mining: Plugin 1 - Device 1 (GeForce GTX 1070 Ti) at Cuck(at)oo29 - Status: OK : Last Graph time: 0.330809552s; Graphs per second: 3.023 - Total Attempts: 16
Feb 15 09:06:57.078 DEBG Mining: Plugin 2 - Device 2 (GeForce GTX 1070 Ti) at Cuck(at)oo29 - Status: OK : Last Graph time: 0.328070426s; Graphs per second: 3.048 - Total Attempts: 16
Feb 15 09:06:57.078 DEBG Mining: Plugin 3 - Device 3 (GeForce GTX 1070 Ti) at Cuck(at)oo29 - Status: OK : Last Graph time: 0.33730199s; Graphs per second: 2.965 - Total Attempts: 15
Feb 15 09:06:57.078 DEBG Mining: Plugin 4 - Device 4 (GeForce GTX 1070 Ti) at Cuck(at)oo29 - Status: OK : Last Graph time: 0.331406143s; Graphs per second: 3.017 - Total Attempts: 16
Feb 15 09:06:57.078 DEBG Mining: Plugin 5 - Device 5 (GeForce GTX 1070 Ti) at Cuck(at)oo29 - Status: OK : Last Graph time: 0.325896211s; Graphs per second: 3.068 - Total Attempts: 16
Feb 15 09:06:57.078 DEBG Mining: Plugin 6 - Device 6 (GeForce GTX 1070 Ti) at Cuck(at)oo29 - Status: OK : Last Graph time: 0.329159782s; Graphs per second: 3.038 - Total Attempts: 16
Feb 15 09:06:57.078 DEBG Mining: Plugin 7 - Device 7 (GeForce GTX 1070 Ti) at Cuck(at)oo29 - Status: OK : Last Graph time: 0.339697315s; Graphs per second: 2.944 - Total Attempts: 15
Feb 15 09:06:57.078 INFO Mining: Cuck(at)oo at 24.15462744557969 gps (graphs per second)
Feb 15 09:07:00.081 DEBG Mining: Plugin 0 - Device 0 (GeForce GTX 1070 Ti) at Cuck(at)oo29 - Status: OK : Last Graph time: 0.355212424s; Graphs per second: 2.815 - Total Attempts: 25
Feb 15 09:07:00.081 DEBG Mining: Plugin 1 - Device 1 (GeForce GTX 1070 Ti) at Cuck(at)oo29 - Status: OK : Last Graph time: 0.326584874s; Graphs per second: 3.062 - Total Attempts: 26
Feb 15 09:07:00.081 DEBG Mining: Plugin 2 - Device 2 (GeForce GTX 1070 Ti) at Cuck(at)oo29 - Status: OK : Last Graph time: 0.339973913s; Graphs per second: 2.941 - Total Attempts: 25
Feb 15 09:07:00.081 DEBG Mining: Plugin 3 - Device 3 (GeForce GTX 1070 Ti) at Cuck(at)oo29 - Status: OK : Last Graph time: 0.350344427s; Graphs per second: 2.854 - Total Attempts: 24
Feb 15 09:07:00.081 DEBG Mining: Plugin 4 - Device 4 (GeForce GTX 1070 Ti) at Cuck(at)oo29 - Status: OK : Last Graph time: 0.32686267s; Graphs per second: 3.059 - Total Attempts: 25
Feb 15 09:07:00.081 DEBG Mining: Plugin 5 - Device 5 (GeForce GTX 1070 Ti) at Cuck(at)oo29 - Status: OK : Last Graph time: 0.326837733s; Graphs per second: 3.060 - Total Attempts: 25
Feb 15 09:07:00.081 DEBG Mining: Plugin 6 - Device 6 (GeForce GTX 1070 Ti) at Cuck(at)oo29 - Status: OK : Last Graph time: 0.324935648s; Graphs per second: 3.078 - Total Attempts: 25
Feb 15 09:07:00.081 DEBG Mining: Plugin 7 - Device 7 (GeForce GTX 1070 Ti) at Cuck(at)oo29 - Status: OK : Last Graph time: 0.329127424s; Graphs per second: 3.038 - Total Attempts: 24
Feb 15 09:07:00.081 INFO Mining: Cuck(at)oo at 23.907824572264317 gps (graphs per second)

```

**Comment by hashmap** [comment] 2019-02-15 13:33
Thanks! Duplicate of #190

**Closed by hashmap** 2019-02-15 13:33 UTC
